query ListBooks { 
  robinsonCrusoe:getBookById(id: "8u12h3871h3"){ 
    ...bookDetail 
  } 
  treasureIsland:getBookById(id: "8u12aa87fsd"){ 
    ...bookDetail 
  } 
  pocahontas:getBookById(id: "4sda38731aa"){ 
    ...bookDetail 
  }  
} 