{
    search{
        __typename
        ... on Person{
            firstName
            lastName
        }
        ... on Company{
            name
        }
        ... on Group{
            groupName
            category
        }
    }
}